# Generated by Django 5.1 on 2024-08-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0002_alter_types_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mushrooms',
            table='mushrooms',
        ),
    ]
