# Generated by Django 5.1 on 2024-08-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0003_alter_mushrooms_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushrooms',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mushrooms',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mushrooms',
            name='is_it_good',
            field=models.CharField(max_length=50, null=True, verbose_name='Лекарственное применение'),
        ),
        migrations.AlterField(
            model_name='mushrooms',
            name='latin',
            field=models.CharField(max_length=50, verbose_name='Название на латыни'),
        ),
        migrations.AlterField(
            model_name='mushrooms',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mushrooms',
            name='syn',
            field=models.CharField(max_length=120, null=True, verbose_name='Синонимы'),
        ),
    ]
