# Generated by Django 5.1 on 2024-08-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0005_alter_mushrooms_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название типа'),
        ),
    ]
