# Generated by Django 5.1 on 2024-08-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0006_alter_types_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushrooms',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushroom_db.types', verbose_name='Тип'),
        ),
    ]
