# Generated by Django 5.1 on 2024-08-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0008_types_en_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mushrooms',
            options={'verbose_name': 'Гриб', 'verbose_name_plural': 'Грибы'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Типа', 'verbose_name_plural': 'Типы'},
        ),
    ]
