# Generated by Django 5.1 on 2024-08-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0009_alter_mushrooms_options_alter_types_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.RemoveField(
            model_name='mushrooms',
            name='is_it_good',
        ),
        migrations.AddField(
            model_name='mushrooms',
            name='extras',
            field=models.CharField(max_length=50, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='mushrooms',
            name='latin',
            field=models.CharField(max_length=100, verbose_name='Название на латыни'),
        ),
    ]
