# Generated by Django 5.1 on 2024-08-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0010_alter_types_options_remove_mushrooms_is_it_good_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushrooms',
            name='extras',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='mushrooms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mushrooms',
            name='latin',
            field=models.CharField(max_length=150, verbose_name='Название на латыни'),
        ),
        migrations.AlterField(
            model_name='mushrooms',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mushrooms',
            name='syn',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Синонимы'),
        ),
    ]
