# Generated by Django 5.1 on 2024-08-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0011_alter_mushrooms_extras_alter_mushrooms_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushrooms',
            name='url',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='mushrooms',
            name='extras',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Примечания'),
        ),
    ]
