# Generated by Django 5.1 on 2024-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0012_mushrooms_url_alter_mushrooms_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushrooms',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
