# Generated by Django 5.1 on 2024-08-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0014_remove_mushrooms_full_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomsDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='mushrooms',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
