# Generated by Django 5.1 on 2024-08-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0016_delete_mushroomsdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=2, verbose_name='Заглавная буква')),
                ('en_name', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Алфавит',
                'verbose_name_plural': 'Алфавиты',
                'db_table': 'alphabet',
            },
        ),
    ]
