# Generated by Django 5.1 on 2024-08-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_db', '0017_alphabet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alphabet',
            old_name='en_name',
            new_name='url',
        ),
    ]
