# Generated by Django 5.1 on 2024-08-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, verbose_name='Название типа статьи')),
                ('url', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип статьи',
                'verbose_name_plural': 'Типы статей',
                'db_table': 'article_types',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название типа статьи')),
                ('url', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Автора',
                'verbose_name_plural': 'Авторы',
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='article_image/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание статьи')),
                ('url', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='URL')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushroom_articles.article_types', verbose_name='Тип статьи')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushroom_articles.authors', verbose_name='Автор у этой статьи')),
            ],
            options={
                'verbose_name': 'Гриб',
                'verbose_name_plural': 'Грибы',
                'db_table': 'articles',
            },
        ),
    ]
