# Generated by Django 5.1 on 2024-08-28 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_articles', '0002_alter_articles_options_alter_articles_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя картинки для слайдера')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images/', verbose_name='Изображение для слайдера')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushroom_articles.article_types', verbose_name='Тип статьи, для которой сделана картинка')),
            ],
            options={
                'verbose_name': 'Картинку',
                'verbose_name_plural': 'Картинки',
                'db_table': 'slider_images',
            },
        ),
    ]
