# Generated by Django 5.1 on 2024-08-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_articles', '0003_sliders'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='url',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='URL'),
        ),
    ]
