# Generated by Django 5.1 on 2024-08-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_articles', '0004_sliders_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание статьи'),
        ),
    ]
